Заданьки #1
spendy-github/123 pull request #4
Opened 2024-02-07 07:35 UTC by spendy-github

2024-02-08 21:36 UTC, greatstudentkaze requested changes
первая итерация

2024-02-08 21:36 UTC, greatstudentkaze commented on blocks/about.css
> +.about__feature__projects{
не может быть элемент у элемента по БЭМ

2024-02-08 21:36 UTC, greatstudentkaze commented on blocks/about.css
> +    width: 0;
этот класс и стиль для чего вообще?

2024-02-08 21:36 UTC, greatstudentkaze commented on blocks/about.css
> +    text-align: left;
это дефолтное значение, зачем его писать?

2024-02-08 21:36 UTC, greatstudentkaze commented on blocks/body.css
> +        grid-template-columns: 1fr 1fr 1fr 1fr;
repeat(4, 1fr)

2024-02-08 21:36 UTC, greatstudentkaze commented on blocks/feedback.css
> +        grid-column: 1 / 5;
если ты хочешь растянуть элемент от первой до последней колонки, то можно использовать grid-column: 1 / -1

2024-02-08 21:36 UTC, greatstudentkaze commented on blocks/footer.css
> +        margin-top: 60px;
у блоков по хорошему не должно быть внешней геометрии, только внутренняя (padding-top)

2024-02-08 21:36 UTC, greatstudentkaze commented on blocks/footer.css
> +        padding-bottom: 16px;
посмотри кодстайл академии и старайся ему соответствовать пока https://codeguide.academy/html-css.html#css

2024-02-08 21:36 UTC, greatstudentkaze commented on blocks/projects.css
> +        width: 100%;
разве это влияет на что-то?

2024-02-08 21:36 UTC, greatstudentkaze commented on blocks/projects.css
> +        grid-column: 21 / 25;
чего... у тебя ведь всего 4 колонки

2024-02-08 21:36 UTC, greatstudentkaze commented on images/ellipsis.svg
это menu скорее

2024-02-08 21:36 UTC, greatstudentkaze commented on index.html
> +    <ul class="header__list">
ul не выровнен

2024-02-08 21:36 UTC, greatstudentkaze commented on index.html
> +      <img class="header__image-logo" src="images/logo.svg" width="70px" height="74px" alt="Лого">
img снова уехал влево

2024-02-08 21:36 UTC, greatstudentkaze commented on index.html
> +<section class="about grid">
посмотри отступы и вложенность везде

2024-02-08 21:36 UTC, greatstudentkaze commented on index.html
> +    <p class="hero-section__titul-subtutle-text">Мы можем произвести любую мебель для вашего проекта и найти производственное решение любой задумки.</p>
1. subtutle -> subtitle
2. зачем div вокруг p?

2024-02-08 21:38 UTC, greatstudentkaze commented on blocks/about.css
> +@media screen and (max-width:480px){
сделай css property для 480px и назови как-нибудь типа --mobile-width-only

см. пример https://github.com/greatstudentkaze/cat-energy/blob/master/source/sass/blocks/main-nav.scss#L107

зачем так? чтобы если вдруг брейкпоинт поменяется – поменять менять сразу везде

2024-02-10 04:14 UTC, spendy-github commented on index.html
> +      <p class="footer__legal-docs">
пофиксил

2024-02-10 04:21 UTC, spendy-github commented on index.html
> +</section>
тут все ок. сектион открывающий в этом же поле лежит. + я буду оформлять код так будто бы он не лежит в бади. ну типо нахуя мне линия слева вот эта лишняя во все ебало. итак понятно что это бади. поэтому левый отступ бади мне не нужен . он наоборот только сбивает если в код смотреть. и у меня кароче бади лежит в том же отступе что и сектионы и футеры и хедеры

2024-02-10 04:23 UTC, spendy-github commented on index.html
> -    <input class="feedback__input" type="text" required name="Text" placeholder="Имя">
у меня эта строчка есть. я хз хули она тут красная

2024-02-10 04:25 UTC, spendy-github commented on index.html
> -    <input class="feedback__input" type="text" required name="Text" placeholder="Имя">
случайно походу тайп текст удалил

2024-02-10 04:26 UTC, spendy-github commented on index.html
> +  <div class="reviews__item reviews--third ">
убрал

2024-02-10 04:28 UTC, spendy-github commented on index.html
> +  <div class="reviews__item reviews--first ">
пофиксил

2024-02-10 04:32 UTC, spendy-github commented on blocks/about.css
> +.about__feature__projects{
удалил . проджекст ваще лишняя какая то хуйня

2024-02-10 04:39 UTC, spendy-github commented on blocks/about.css
> +    width: 0;
без класса
https://sun9-65.userapi.com/impg/1qeyHvt7mWGl5vDn7wk9Fk68UB92Ze1Y2IjkDg/-LSC64gLFOY.jpg?size=253x99&quality=96&sign=521935890c22a761f8dc3ee012a57436&type=album
с классом 
https://sun9-65.userapi.com/impg/1qeyHvt7mWGl5vDn7wk9Fk68UB92Ze1Y2IjkDg/-LSC64gLFOY.jpg?size=253x99&quality=96&sign=521935890c22a761f8dc3ee012a57436&type=album

щас я просто задал ширину в about__feature__class и тоже все норм стоит. это просто околопервый блок. я тогда еще по другому делал

2024-02-10 04:40 UTC, spendy-github commented on blocks/about.css
> +    width: 0;
класс удалил

2024-02-10 04:43 UTC, spendy-github commented on blocks/about.css
> +    text-align: left;
дефолтное ток текст алайн лефт

2024-02-10 04:43 UTC, spendy-github commented on blocks/about.css
> +    text-align: left;
ну бля я ставлю все эти дефолтные параметры чтобы у меня точно все не уехало. я просто проецирую картинку в голове и пишу просто по ней как точно должно все встать

2024-02-10 04:45 UTC, spendy-github commented on blocks/body.css
> +        grid-template-columns: 1fr 1fr 1fr 1fr;
пофиксил

2024-02-10 04:46 UTC, spendy-github commented on blocks/feedback.css
> +        grid-column: 1 / 5;
в -1 два символа а в 5 всего один . не нагружай css бро

2024-02-10 04:54 UTC, spendy-github commented on blocks/feedback.css
> +        grid-column: 1 / 5;
поменял на -1. но это неправильное мышление по моему броуди. потому что в свапе карточек я колонки до 25 прописал. если бы я изначально был научен писать последнюю колонку на -1 а не на последнюю цифру,то не смог бы придумать такую технологию свапа карточек

2024-02-10 05:02 UTC, spendy-github commented on blocks/footer.css
> +        margin-top: 60px;
Это отступы между блоками . в макете так же. с пединг топом это будет ваще хуйня выходить 
Если делать с педингом надо будет каждому блоку прописывать сначала марджин 0 чтобы указать пединг. это же тупо пиздец 
https://sun9-68.userapi.com/impg/fRcVT6p614R21hK61cEwc4Va5ggChzUT7rBdrw/kifaDjVFQek.jpg?size=622x485&quality=96&sign=fd665711e331c5ef4462982fc9468bb4&type=album

2024-02-10 05:09 UTC, spendy-github commented on blocks/footer.css
> +        padding-bottom: 16px;
padding: 0 51px 16px; типо дыа?

2024-02-10 05:09 UTC, spendy-github commented on blocks/footer.css
> +        padding-bottom: 16px;
ну я чекну статью фулл

2024-02-10 05:11 UTC, spendy-github commented on blocks/footer.css
> +        padding-bottom: 16px;
заменил если че на один педдинг

2024-02-10 05:13 UTC, spendy-github commented on blocks/projects.css
> +        width: 100%;
убрал

2024-02-10 05:13 UTC, spendy-github commented on blocks/projects.css
> +        grid-column: 21 / 25;
ТЫ ДОЛБАЕБ ДА ЧЭЛ?

2024-02-10 05:13 UTC, spendy-github commented on blocks/projects.css
> +        grid-column: 21 / 25;
у меня бесконечное количество колонок

2024-02-10 05:16 UTC, spendy-github commented on blocks/projects.css
> +        width: 100%;
убрал

2024-02-10 05:17 UTC, spendy-github commented on blocks/projects.css
> +        grid-column: 21 / 25;
это самокрутка чтобы картинки делали крутивки

2024-02-10 05:20 UTC, spendy-github commented on images/ellipsis.svg
сделал меню

2024-02-10 05:21 UTC, spendy-github commented on index.html
> +    <ul class="header__list">
выровнял

2024-02-10 05:22 UTC, spendy-github commented on index.html
> +      <img class="header__image-logo" src="images/logo.svg" width="70px" height="74px" alt="Лого">
пофиксил

2024-02-10 05:24 UTC, spendy-github commented on index.html
> +<section class="about grid">
посмотрел

2024-02-10 05:24 UTC, spendy-github commented on index.html
> +<section class="about grid">
но у меня все секции там же стартуют что и бади мне так лучше видится все

2024-02-10 05:38 UTC, spendy-github commented on index.html
> +    <p class="hero-section__titul-subtutle-text">Мы можем произвести любую мебель для вашего проекта и найти производственное решение любой задумки.</p>
чтобы задать колонку  
я когда пишу допустим p display:block и колонки задаю он нихуя не встает в эти колонки я хз почему

2024-02-10 05:43 UTC, spendy-github commented on index.html
> +    <p class="hero-section__titul-subtutle-text">Мы можем произвести любую мебель для вашего проекта и найти производственное решение любой задумки.</p>
убрал. первопроходом хуйни всякой понаписал броуди

2024-02-10 07:34 UTC, spendy-github commented on blocks/about.css
> +@media screen and (max-width:480px){
ты меня наебучки броу 
зато узнал шо такое рут

2024-02-10 09:29 UTC, greatstudentkaze commented on index.html
> +    <h2 class="about__header-adaptive">О компании</h2>
ебать дизайнер долбоеб конечно

2024-02-10 09:31 UTC, greatstudentkaze commented on index.html
> +      <div class="about__feature__class">
не может быть элемент элемента
сделай так:
![CleanShot 2024-02-10 at 12 30 55@2x](https://github.com/spendy-github/123/assets/51622226/9c8d543e-37db-49c2-b30a-f97e0300b18f)

2024-02-10 09:35 UTC, greatstudentkaze commented on index.html
> +    <h1 class="hero-section__titul-header">Эксклюзивная и нестандартная мебель для дома</h1>
titul убери не позорься б роу

2024-02-10 09:40 UTC, greatstudentkaze commented on blocks/about.css
> +    text-align: left;
удаляй говорю

2024-02-10 09:40 UTC, greatstudentkaze commented on blocks/body.css
> +    --mobile-width-only: 480px;
нигде не используется, удаляй

2024-02-10 09:41 UTC, greatstudentkaze commented on blocks/footer.css
> +        margin-top: 60px;
когда css буду ревьюить покажу почему лучше сделать через padding

2024-02-10 09:42 UTC, greatstudentkaze commented on blocks/projects.css
> +        grid-column: 21 / 25;
хуйня какая-то , потом когда css буду ревьюить посмотрю

2024-02-10 09:46 UTC, greatstudentkaze commented on blocks/feedback.css
> +        grid-column: 1 / 5;
Ахахахххахаха

2024-02-10 09:49 UTC, greatstudentkaze commented on blocks/footer.css
> +        padding-bottom: 16px;
нет, я про порядок свойств 
![image](https://github.com/spendy-github/123/assets/51622226/0bae9e2d-1a4e-4c8e-a272-bba3a4be506b)

но то что короткую версию сделал это тоже ок

2024-02-10 11:37 UTC, spendy-github commented on index.html
> +      <div class="about__feature__class">
убрал обертку лишнюю. теперь только абаут фьючр

2024-02-10 11:40 UTC, spendy-github commented on index.html
> +    <h1 class="hero-section__titul-header">Эксклюзивная и нестандартная мебель для дома</h1>
убрал

2024-02-10 11:44 UTC, spendy-github commented on blocks/body.css
> +    --mobile-width-only: 480px;
удалил

2024-02-10 12:25 UTC, greatstudentkaze commented on index.html
> +      <div class="about__feature__class">
фича а не фьючр ток

2024-02-10 12:25 UTC, merged