best-version
spendy-github/123 pull request #5
Opened 2024-02-10 14:11 UTC by spendy-github

2024-02-10 14:17 UTC, greatstudentkaze commented on blocks/header.css
> +    display: none;
тут чето не так и выше тоже самое

2024-02-10 14:18 UTC, greatstudentkaze commented on blocks/projects.css
> +.colonka--6 {
column а не colonka

2024-02-10 14:19 UTC, greatstudentkaze commented on blocks/projects.css
> +    grid-template-rows: repeat(1fr,3);
сначала количество повторений, потом размер
https://developer.mozilla.org/en-US/docs/Web/CSS/repeat

2024-02-10 14:19 UTC, greatstudentkaze commented on blocks/projects.css
> +    grid-template-rows: repeat(1fr,3);
есть ли смысл в этом правиле тут вообще? если grid template rows уберешь разве что-то измениться?

2024-02-13 13:14 UTC, spendy-github commented on blocks/header.css
> +    display: none;
это чтобы они пропадали на мобилке

2024-02-13 13:24 UTC, spendy-github commented on blocks/projects.css
> +.colonka--6 {
сделал

2024-02-13 13:25 UTC, spendy-github commented on blocks/projects.css
> +    grid-template-rows: repeat(1fr,3);
убрал брох. ты как всегда прав

2024-02-13 13:25 UTC, spendy-github commented on blocks/projects.css
> +    grid-template-rows: repeat(1fr,3);
я хз хули она там была

2024-02-15 16:56 UTC, greatstudentkaze commented on blocks/header.css
> +    display: none;
я про то, что оно съехало внутрь

2024-02-15 17:00 UTC, greatstudentkaze commented on index.html
> +  <script src="window.js"> </script>
почитай про async и defer + зачем коммитить пустой файл?

2024-02-15 17:01 UTC, greatstudentkaze commented on blocks/body.css
> +.input:focus ~ label {
почему это в body? создай блок input и там храни эти стили

2024-02-15 17:01 UTC, greatstudentkaze commented on blocks/body.css
> +    cursor: default ;
пробел

2024-02-15 17:02 UTC, greatstudentkaze commented on blocks/body.css
> +    --black-color: #000000;
можно без -color во всех

2024-02-15 17:02 UTC, greatstudentkaze commented on blocks/body.css
> +    --gray-color: #DDD7C0;
давай в одном регистре hex писать #ddd7c0

2024-02-15 17:03 UTC, greatstudentkaze commented on blocks/feedback.css
> +    position: absolute;
стили позиционирования над гридом

2024-02-15 17:03 UTC, greatstudentkaze commented on blocks/body.css
> +:root {
вынеси в отдельный файл variables

2024-02-15 17:04 UTC, greatstudentkaze commented on blocks/feedback.css
> +    background-color: #FFF;
переменная

2024-02-15 17:04 UTC, greatstudentkaze commented on blocks/feedback.css
> +    border-bottom: 1px solid #212529;
переменная

2024-02-15 17:04 UTC, greatstudentkaze commented on blocks/feedback.css
> +    font-family: Verdana, sans-serif;
переменная

2024-02-15 17:04 UTC, greatstudentkaze commented on blocks/feedback.css
> +    background-color: #BFE2FF;
переменная

2024-02-15 17:04 UTC, greatstudentkaze commented on blocks/feedback.css
> +    background-color:#212529;
переменная и пробел

2024-02-15 17:04 UTC, greatstudentkaze commented on blocks/feedback.css
> +    color: aliceblue;
какая алиса голубая? возьми цвет с макета и в переменную тож

2024-02-15 17:05 UTC, greatstudentkaze commented on blocks/feedback.css
> +    background-color: #CBC6B2;
переменная

2024-02-15 17:05 UTC, greatstudentkaze commented on blocks/feedback.css
> +    background: #DDD7C0;
background-color и в переменную

2024-02-15 17:05 UTC, greatstudentkaze commented on blocks/feedback.css
> +        background-color: #F9C67B;
переменная

2024-02-15 17:06 UTC, greatstudentkaze commented on blocks/feedback.css
> +        background-color: inherit;
почему inherit? что пытаешься решить этим?

2024-02-15 17:06 UTC, greatstudentkaze commented on blocks/feedback.css
> +    .feedback__button{
пробелы перед кавычками везде проверь

2024-02-15 17:07 UTC, greatstudentkaze commented on blocks/header.css
> +    color:#212529;
переменная + все слиплось

2024-02-15 17:07 UTC, greatstudentkaze commented on blocks/header.css
> +    box-shadow: 1px 1px 10px rgb(0, 255, 0);
hex вмеcто rgb и как будто в переменную тоже

2024-02-15 17:07 UTC, greatstudentkaze commented on blocks/header.css
> +    border-radius: 5em;
зачем em?

2024-02-15 17:08 UTC, greatstudentkaze commented on blocks/reviews.css
> +    border: 1px solid black;
переменная

2024-02-15 17:09 UTC, greatstudentkaze commented on blocks/reviews.css
> +    height: 327px;
не надо ограничивать по высоте, иначе если в отзыв контент добавится, то он будет обрезан

2024-02-15 17:09 UTC, greatstudentkaze commented on blocks/workflow.css
> +    border-bottom: 1px solid black;
переменная

2024-02-15 17:12 UTC, greatstudentkaze commented on index.html
> +  <section class="feedback grid --background-form">
про какой нахуй --bacground-form, мы же обсудили

2024-02-15 17:13 UTC, greatstudentkaze commented on index.html
> +        <label class="feedback__label" for="feedback__input-name"> Имя</label>
пробел зачем перед Имя?

2024-02-15 17:13 UTC, greatstudentkaze commented on index.html
> +        <input class="feedback__input" id="feedback__input-name" placeholder=" " type="text" required name="Text">
убери placeholder прост

2024-02-15 17:14 UTC, greatstudentkaze commented on index.html
> +      <button class="feedback__button" type="submit" method>Отправить заявку</button>
method нет у кнопки

2024-02-15 17:15 UTC, greatstudentkaze requested changes
см. комменты

2024-02-16 17:32 UTC, spendy-github commented on blocks/header.css
> +    display: none;
сьехало бро. базару 0. пофиксил

2024-02-17 17:34 UTC, greatstudentkaze commented on blocks/feedback.css
> +    background-color: inherit;
зачем это используешь? что без него будет?

2024-02-17 17:35 UTC, greatstudentkaze commented on blocks/projects.css
> +    background-color: rgba(33, 37, 41, 0.5);;
в переменную
и две точки с запятой

2024-02-17 17:39 UTC, greatstudentkaze commented on index.html
> +        <input class="feedback__input" type="email" name="email" placeholder="" required name="E-mail">
два атрибута name

2024-02-17 17:40 UTC, greatstudentkaze commented on index.html
> +    <form class="feedback__application" method="get">
не GET тут нужен

https://htmlacademy.ru/blog/html-tags/form

2024-02-17 17:42 UTC, greatstudentkaze commented on blocks/body.css
> +    scroll-behavior: smooth;
отступы

2024-02-18 11:10 UTC, merged